#! /usr/bin/env node

var ThingHolder = require('./thingHolder');

var tags = ['a', 'b', 'c'];
var collector = new ThingHolder(tags);

collector.on('add', function onAdd(ev) {
    console.log('Added something %s', ev);
})

collector.on('invalidTag', function onInvalidTag(ev) {
    console.log('Ignored attempt to add thing for invalid tag %s', ev);
})

collector.on('complete', function onComplete(ev) {
    console.log('Complete: %s', ev);
    console.log(JSON.stringify(collector.things, null, 2));
})

collector.add('a', "This is an A");
collector.add('b', "This is an B");
collector.add('d', "This is an D");
collector.add('c', "This is an C");



